// Automatically generated using: https://gitlab.cern.ch/alpapado/rd53b-register-table-code-generator

#include "RD53BCMSRegisters.h"


namespace Ph2_HwDescription {

namespace RD53BConstants {

const std::array<Register, 256> CMSRegisters::Regs = {
    Register{ "PIX_PORTAL", 0, 16, 0, true, RegType::Special }, 
    Register{ "REGION_COL", 1, 8, 0, false, RegType::ReadWrite }, 
    Register{ "REGION_ROW", 2, 9, 0, false, RegType::ReadWrite }, 
    Register{ "PIX_MODE", 3, 5, 10, false, RegType::ReadWrite }, 
    Register{ "PIX_DEFAULT_CONFIG", 4, 16, 0, false, RegType::Special }, 
    Register{ "PIX_DEFAULT_CONFIG_B", 5, 16, 0, false, RegType::Special }, 
    Register{ "GCR_DEFAULT_CONFIG", 6, 16, 0, false, RegType::Special }, 
    Register{ "GCR_DEFAULT_CONFIG_B", 7, 16, 0, false, RegType::Special }, 
    Register{ "DAC_PREAMP_L_DIFF", 8, 10, 50, false, RegType::ReadWrite }, 
    Register{ "DAC_PREAMP_R_DIFF", 9, 10, 50, false, RegType::ReadWrite }, 
    Register{ "DAC_PREAMP_TL_DIFF", 10, 10, 50, false, RegType::ReadWrite }, 
    Register{ "DAC_PREAMP_TR_DIFF", 11, 10, 50, false, RegType::ReadWrite }, 
    Register{ "DAC_PREAMP_T_DIFF", 12, 10, 50, false, RegType::ReadWrite }, 
    Register{ "DAC_PREAMP_M_DIFF", 13, 10, 50, false, RegType::ReadWrite }, 
    Register{ "DAC_PRECOMP_DIFF", 14, 10, 50, false, RegType::ReadWrite }, 
    Register{ "DAC_COMP_DIFF", 15, 10, 50, false, RegType::ReadWrite }, 
    Register{ "DAC_VFF_DIFF", 16, 10, 100, false, RegType::ReadWrite }, 
    Register{ "DAC_TH1_L_DIFF", 17, 10, 100, false, RegType::ReadWrite }, 
    Register{ "DAC_TH1_R_DIFF", 18, 10, 100, false, RegType::ReadWrite }, 
    Register{ "DAC_TH1_M_DIFF", 19, 10, 100, false, RegType::ReadWrite }, 
    Register{ "DAC_TH2_DIFF", 20, 10, 0, false, RegType::ReadWrite }, 
    Register{ "DAC_LCC_DIFF", 21, 10, 100, false, RegType::ReadWrite }, 
    Register{ "DAC_PREAMP_L_LIN", 22, 10, 150, false, RegType::ReadWrite }, 
    Register{ "DAC_PREAMP_R_LIN", 23, 10, 150, false, RegType::ReadWrite }, 
    Register{ "DAC_PREAMP_TL_LIN", 24, 10, 150, false, RegType::ReadWrite }, 
    Register{ "DAC_PREAMP_TR_LIN", 25, 10, 150, false, RegType::ReadWrite }, 
    Register{ "DAC_PREAMP_T_LIN", 26, 10, 150, false, RegType::ReadWrite }, 
    Register{ "DAC_PREAMP_M_LIN", 27, 10, 150, false, RegType::ReadWrite }, 
    Register{ "DAC_FC_LIN", 28, 10, 20, false, RegType::ReadWrite }, 
    Register{ "DAC_KRUM_CURR_LIN", 29, 10, 70, false, RegType::ReadWrite }, 
    Register{ "DAC_REF_KRUM_LIN", 30, 10, 360, false, RegType::ReadWrite }, 
    Register{ "DAC_COMP_LIN", 31, 10, 80, false, RegType::ReadWrite }, 
    Register{ "DAC_COMP_TA_LIN", 32, 10, 900, false, RegType::ReadWrite }, 
    Register{ "DAC_GDAC_L_LIN", 33, 10, 900, false, RegType::ReadWrite }, 
    Register{ "DAC_GDAC_R_LIN", 34, 10, 900, false, RegType::ReadWrite }, 
    Register{ "DAC_GDAC_M_LIN", 35, 10, 900, false, RegType::ReadWrite }, 
    Register{ "DAC_LDAC_LIN", 36, 10, 130, false, RegType::ReadWrite }, 
    Register{ "LEACKAGE_FEEDBACK", 37, 2, 0, false, RegType::ReadWrite }, 
    Register{ "VOLTAGE_TRIM", 38, 10, 136, false, RegType::ReadWrite }, 
    Register{ "EnCoreCol_3", 39, 6, 18, false, RegType::Special }, 
    Register{ "EnCoreCol_2", 40, 16, 18724, false, RegType::Special }, 
    Register{ "EnCoreCol_1", 41, 16, 37449, false, RegType::Special }, 
    Register{ "EnCoreCol_0", 42, 16, 9362, false, RegType::Special }, 
    Register{ "EnCoreColumnReset_3", 43, 6, 0, false, RegType::Special }, 
    Register{ "EnCoreColumnReset_2", 44, 16, 0, false, RegType::Special }, 
    Register{ "EnCoreColumnReset_1", 45, 16, 0, false, RegType::Special }, 
    Register{ "EnCoreColumnReset_0", 46, 16, 0, false, RegType::Special }, 
    Register{ "TriggerConfig", 47, 10, 500, false, RegType::ReadWrite }, 
    Register{ "SelfTriggerConfig_1", 48, 6, 17, false, RegType::ReadWrite }, 
    Register{ "SelfTriggerConfig_0", 49, 15, 3201, false, RegType::ReadWrite }, 
    Register{ "HitOrPatternLUT", 50, 16, 0, false, RegType::ReadWrite }, 
    Register{ "ReadTriggerConfig", 51, 14, 1000, false, RegType::ReadWrite }, 
    Register{ "TruncationTimeoutConf", 52, 12, 0, false, RegType::ReadWrite }, 
    Register{ "CalibrationConfig", 53, 8, 64, false, RegType::ReadWrite }, 
    Register{ "CLK_DATA_FINE_DELAY", 54, 12, 0, false, RegType::ReadWrite }, 
    Register{ "VCAL_HIGH", 55, 12, 500, false, RegType::ReadWrite }, 
    Register{ "VCAL_MED", 56, 12, 300, false, RegType::ReadWrite }, 
    Register{ "MEAS_CAP", 57, 3, 0, false, RegType::ReadWrite }, 
    Register{ "CdrConf", 58, 4, 8, false, RegType::Special }, 
    Register{ "ClockEnableConf", 59, 12, 4095, false, RegType::ReadWrite }, 
    Register{ "ChSyncConf", 60, 5, 16, false, RegType::ReadWrite }, 
    Register{ "GlobalPulseConf", 61, 16, 0, false, RegType::ReadWrite }, 
    Register{ "GlobalPulseWidth", 62, 9, 1, false, RegType::ReadWrite }, 
    Register{ "ServiceDataConf", 63, 9, 50, false, RegType::Special }, 
    Register{ "ToTConfig", 64, 13, 0, false, RegType::ReadWrite }, 
    Register{ "PrecisionToTEnable_3", 65, 6, 0, false, RegType::ReadWrite }, 
    Register{ "PrecisionToTEnable_2", 66, 16, 0, false, RegType::ReadWrite }, 
    Register{ "PrecisionToTEnable_1", 67, 16, 0, false, RegType::ReadWrite }, 
    Register{ "PrecisionToTEnable_0", 68, 16, 0, false, RegType::ReadWrite }, 
    Register{ "DataMerging", 69, 13, 385, false, RegType::ReadWrite }, 
    Register{ "DataMergingMux", 70, 16, 58596, false, RegType::ReadWrite }, 
    Register{ "EnCoreColumnCalibration_3", 71, 6, 63, false, RegType::Special }, 
    Register{ "EnCoreColumnCalibration_2", 72, 16, 65535, false, RegType::Special }, 
    Register{ "EnCoreColumnCalibration_1", 73, 16, 65535, false, RegType::Special }, 
    Register{ "EnCoreColumnCalibration_0", 74, 16, 65535, false, RegType::Special }, 
    Register{ "DataConcentratorConf", 75, 12, 272, false, RegType::ReadWrite }, 
    Register{ "CoreColEncoderConf", 76, 9, 0, false, RegType::ReadWrite }, 
    Register{ "EnHitsRemoval_3", 77, 6, 0, false, RegType::ReadWrite }, 
    Register{ "EnHitsRemoval_2", 78, 16, 0, false, RegType::ReadWrite }, 
    Register{ "EnHitsRemoval_1", 79, 16, 0, false, RegType::ReadWrite }, 
    Register{ "EnHitsRemoval_0", 80, 16, 0, false, RegType::ReadWrite }, 
    Register{ "EnIsolatedHitRemoval_3", 81, 6, 0, false, RegType::ReadWrite }, 
    Register{ "EnIsolatedHitRemoval_2", 82, 16, 0, false, RegType::ReadWrite }, 
    Register{ "EnIsolatedHitRemoval_1", 83, 16, 0, false, RegType::ReadWrite }, 
    Register{ "EnIsolatedHitRemoval_0", 84, 16, 0, false, RegType::ReadWrite }, 
    Register{ "EvenMask", 85, 16, 0, false, RegType::ReadWrite }, 
    Register{ "OddMask", 86, 16, 0, false, RegType::ReadWrite }, 
    Register{ "EfusesConfig", 87, 16, 0, false, RegType::ReadWrite }, 
    Register{ "EfusesWriteData1", 88, 16, 0, false, RegType::ReadWrite }, 
    Register{ "EfusesWriteData0", 89, 16, 0, false, RegType::ReadWrite }, 
    Register{ "AuroraConfig", 90, 14, 359, false, RegType::Special }, 
    Register{ "AURORA_CB_CONFIG1", 91, 8, 255, false, RegType::ReadWrite }, 
    Register{ "AURORA_CB_CONFIG0", 92, 16, 65520, false, RegType::ReadWrite }, 
    Register{ "AURORA_INIT_WAIT", 93, 11, 32, false, RegType::ReadWrite }, 
    Register{ "AuroraAltOutput_1", 94, 4, 0, false, RegType::ReadWrite }, 
    Register{ "AuroraAltOutput_0", 95, 16, 0, false, RegType::ReadWrite }, 
    Register{ "OUTPUT_PAD_CONFIG", 96, 13, 2943, false, RegType::ReadWrite }, 
    Register{ "GP_CMOS_ROUTE", 97, 6, 13, false, RegType::ReadWrite }, 
    Register{ "GP_LVDS_ROUTE_1", 98, 12, 906, false, RegType::ReadWrite }, 
    Register{ "GP_LVDS_ROUTE_0", 99, 12, 128, false, RegType::ReadWrite }, 
    Register{ "DAC_CP_CDR", 100, 10, 40, false, RegType::ReadWrite }, 
    Register{ "DAC_CP_FD_CDR", 101, 10, 400, false, RegType::ReadWrite }, 
    Register{ "DAC_CP_BUFF_CDR", 102, 10, 200, false, RegType::ReadWrite }, 
    Register{ "DAC_VCO_CDR", 103, 10, 1023, false, RegType::ReadWrite }, 
    Register{ "DAC_VCOBUFF_CDR", 104, 10, 500, false, RegType::ReadWrite }, 
    Register{ "SER_SEL_OUT", 105, 8, 85, false, RegType::Special }, 
    Register{ "CML_CONFIG", 106, 8, 1, false, RegType::Special }, 
    Register{ "DAC_CML_BIAS_2", 107, 10, 0, false, RegType::ReadWrite }, 
    Register{ "DAC_CML_BIAS_1", 108, 10, 0, false, RegType::ReadWrite }, 
    Register{ "DAC_CML_BIAS_0", 109, 10, 500, false, RegType::ReadWrite }, 
    Register{ "MonitorConfig", 110, 13, 4095, false, RegType::ReadWrite }, 
    Register{ "ErrWngMask", 111, 8, 0, false, RegType::ReadWrite }, 
    Register{ "MON_SENS_SLDO", 112, 12, 0, false, RegType::ReadWrite }, 
    Register{ "MON_SENS_ACB", 113, 6, 0, false, RegType::ReadWrite }, 
    Register{ "MON_ADC", 114, 9, 16, false, RegType::ReadWrite }, 
    Register{ "DAC_NTC", 115, 10, 100, false, RegType::ReadWrite }, 
    Register{ "HITOR_MASK_3", 116, 6, 0, false, RegType::ReadWrite }, 
    Register{ "HITOR_MASK_2", 117, 16, 0, false, RegType::ReadWrite }, 
    Register{ "HITOR_MASK_1", 118, 16, 0, false, RegType::ReadWrite }, 
    Register{ "HITOR_MASK_0", 119, 16, 0, false, RegType::ReadWrite }, 
    Register{ "AutoRead0", 120, 9, 150, false, RegType::ReadWrite }, 
    Register{ "AutoRead1", 121, 9, 144, false, RegType::ReadWrite }, 
    Register{ "AutoRead2", 122, 9, 132, false, RegType::ReadWrite }, 
    Register{ "AutoRead3", 123, 9, 133, false, RegType::ReadWrite }, 
    Register{ "AutoRead4", 124, 9, 135, false, RegType::ReadWrite }, 
    Register{ "AutoRead5", 125, 9, 138, false, RegType::ReadWrite }, 
    Register{ "AutoRead6", 126, 9, 137, false, RegType::ReadWrite }, 
    Register{ "AutoRead7", 127, 9, 136, false, RegType::ReadWrite }, 
    Register{ "RingOscConfig", 128, 15, 16640, false, RegType::ReadWrite }, 
    Register{ "RingOscRoute", 129, 9, 0, false, RegType::ReadWrite }, 
    Register{ "RING_OSC_A_OUT", 130, 16, 0, true, RegType::ReadOnly }, 
    Register{ "RING_OSC_B_OUT", 131, 16, 0, true, RegType::ReadOnly }, 
    Register{ "BCIDCnt", 132, 16, 0, true, RegType::ReadOnly }, 
    Register{ "TrigCnt", 133, 16, 0, true, RegType::ReadOnly }, 
    Register{ "ReadTrigCnt", 134, 16, 0, true, RegType::ReadOnly }, 
    Register{ "LockLossCnt", 135, 16, 0, true, RegType::ReadOnly }, 
    Register{ "BitFlipWngCnt", 136, 16, 0, true, RegType::ReadOnly }, 
    Register{ "BitFlipErrCnt", 137, 16, 0, true, RegType::ReadOnly }, 
    Register{ "CmdErrCnt", 138, 16, 0, true, RegType::ReadOnly }, 
    Register{ "RdWrFifoErrorCount", 139, 16, 0, true, RegType::ReadOnly }, 
    Register{ "AI_REGION_ROW", 140, 9, 0, true, RegType::ReadOnly }, 
    Register{ "HitOr_3_Cnt", 141, 16, 0, true, RegType::ReadOnly }, 
    Register{ "HitOr_2_Cnt", 142, 16, 0, true, RegType::ReadOnly }, 
    Register{ "HitOr_1_Cnt", 143, 16, 0, true, RegType::ReadOnly }, 
    Register{ "HitOr_0_Cnt", 144, 16, 0, true, RegType::ReadOnly }, 
    Register{ "PixelSEUCnt", 145, 16, 0, true, RegType::ReadOnly }, 
    Register{ "GlobalConfigSEUCnt", 146, 16, 0, true, RegType::ReadOnly }, 
    Register{ "SkippedTriggerCnt", 147, 16, 0, true, RegType::ReadOnly }, 
    Register{ "EfusesReadData1", 148, 16, 0, true, RegType::ReadOnly }, 
    Register{ "EfusesReadData0", 149, 16, 0, true, RegType::ReadOnly }, 
    Register{ "MonitoringDataADC", 150, 12, 0, true, RegType::ReadOnly }, 
    Register{ "SEU00", 151, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU01", 152, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU02", 153, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU03", 154, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU04", 155, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU05", 156, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU06", 157, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU07", 158, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU08", 159, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU_nodel_00", 160, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU_nodel_01", 161, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU_nodel_02", 162, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU_nodel_03", 163, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU_nodel_04", 164, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU_nodel_05", 165, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU_nodel_06", 166, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU_nodel_07", 167, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU_nodel_08", 168, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU_nodel_09", 169, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU_nodel_10", 170, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU_nodel_11", 171, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU_nodel_12", 172, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU_nodel_13", 173, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU_nodel_14", 174, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU_nodel_15", 175, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU_nodel_16", 176, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU_nodel_17", 177, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU_nodel_18", 178, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU_nodel_19", 179, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU_nodel_20", 180, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU_nodel_21", 181, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU_nodel_22", 182, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU_nodel_23", 183, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU_nodel_24", 184, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU_nodel_25", 185, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU_nodel_26", 186, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU_nodel_27", 187, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU_nodel_28", 188, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU_nodel_29", 189, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU_nodel_30", 190, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU_nodel_31", 191, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU00_notmr", 192, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU01_notmr", 193, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU02_notmr", 194, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU03_notmr", 195, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU04_notmr", 196, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU05_notmr", 197, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU06_notmr", 198, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU07_notmr", 199, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU08_notmr", 200, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU09_notmr", 201, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU10_notmr", 202, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU11_notmr", 203, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU12_notmr", 204, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU13_notmr", 205, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU14_notmr", 206, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU15_notmr", 207, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU16_notmr", 208, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU17_notmr", 209, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU18_notmr", 210, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU19_notmr", 211, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU20_notmr", 212, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU21_notmr", 213, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU22_notmr", 214, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU23_notmr", 215, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU24_notmr", 216, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU25_notmr", 217, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU26_notmr", 218, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU27_notmr", 219, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU28_notmr", 220, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU29_notmr", 221, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU30_notmr", 222, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU31_notmr", 223, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU32_notmr", 224, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU33_notmr", 225, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU34_notmr", 226, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU35_notmr", 227, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU36_notmr", 228, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU37_notmr", 229, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU38_notmr", 230, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU39_notmr", 231, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU40_notmr", 232, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU41_notmr", 233, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU42_notmr", 234, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU43_notmr", 235, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU44_notmr", 236, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU45_notmr", 237, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU46_notmr", 238, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU47_notmr", 239, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU48_notmr", 240, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU49_notmr", 241, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU50_notmr", 242, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU51_notmr", 243, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU52_notmr", 244, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU53_notmr", 245, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU54_notmr", 246, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU55_notmr", 247, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU56_notmr", 248, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU57_notmr", 249, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU58_notmr", 250, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU59_notmr", 251, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU60_notmr", 252, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU61_notmr", 253, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU62_notmr", 254, 16, 0, false, RegType::ReadWrite }, 
    Register{ "SEU63_notmr", 255, 16, 0, false, RegType::ReadWrite }
};

const std::unordered_map<std::string, std::vector<RegisterField>> CMSRegisters::vRegs = {
    { "PIX_PORTAL", { { PIX_PORTAL, 0, 16 } } }, 
    { "REGION_COL", { { REGION_COL, 0, 8 } } }, 
    { "REGION_ROW", { { REGION_ROW, 0, 9 } } }, 
    { "PIX_MODE", { { PIX_MODE, 0, 5 } } }, 
    { "EnSEUCount", { { PIX_MODE, 4, 1 } } }, 
    { "HitSampleMode", { { PIX_MODE, 3, 1 } } }, 
    { "Broadcast", { { PIX_MODE, 2, 1 } } }, 
    { "ConfWrConfig", { { PIX_MODE, 1, 1 } } }, 
    { "AutoRow", { { PIX_MODE, 0, 1 } } }, 
    { "PIX_DEFAULT_CONFIG", { { PIX_DEFAULT_CONFIG, 0, 16 } } }, 
    { "PIX_DEFAULT_CONFIG_B", { { PIX_DEFAULT_CONFIG_B, 0, 16 } } }, 
    { "GCR_DEFAULT_CONFIG", { { GCR_DEFAULT_CONFIG, 0, 16 } } }, 
    { "GCR_DEFAULT_CONFIG_B", { { GCR_DEFAULT_CONFIG_B, 0, 16 } } }, 
    { "DAC_PREAMP_L_DIFF", { { DAC_PREAMP_L_DIFF, 0, 10 } } }, 
    { "DAC_PREAMP_R_DIFF", { { DAC_PREAMP_R_DIFF, 0, 10 } } }, 
    { "DAC_PREAMP_TL_DIFF", { { DAC_PREAMP_TL_DIFF, 0, 10 } } }, 
    { "DAC_PREAMP_TR_DIFF", { { DAC_PREAMP_TR_DIFF, 0, 10 } } }, 
    { "DAC_PREAMP_T_DIFF", { { DAC_PREAMP_T_DIFF, 0, 10 } } }, 
    { "DAC_PREAMP_M_DIFF", { { DAC_PREAMP_M_DIFF, 0, 10 } } }, 
    { "DAC_PRECOMP_DIFF", { { DAC_PRECOMP_DIFF, 0, 10 } } }, 
    { "DAC_COMP_DIFF", { { DAC_COMP_DIFF, 0, 10 } } }, 
    { "DAC_VFF_DIFF", { { DAC_VFF_DIFF, 0, 10 } } }, 
    { "DAC_TH1_L_DIFF", { { DAC_TH1_L_DIFF, 0, 10 } } }, 
    { "DAC_TH1_R_DIFF", { { DAC_TH1_R_DIFF, 0, 10 } } }, 
    { "DAC_TH1_M_DIFF", { { DAC_TH1_M_DIFF, 0, 10 } } }, 
    { "DAC_TH2_DIFF", { { DAC_TH2_DIFF, 0, 10 } } }, 
    { "DAC_LCC_DIFF", { { DAC_LCC_DIFF, 0, 10 } } }, 
    { "DAC_PREAMP_L_LIN", { { DAC_PREAMP_L_LIN, 0, 10 } } }, 
    { "DAC_PREAMP_R_LIN", { { DAC_PREAMP_R_LIN, 0, 10 } } }, 
    { "DAC_PREAMP_TL_LIN", { { DAC_PREAMP_TL_LIN, 0, 10 } } }, 
    { "DAC_PREAMP_TR_LIN", { { DAC_PREAMP_TR_LIN, 0, 10 } } }, 
    { "DAC_PREAMP_T_LIN", { { DAC_PREAMP_T_LIN, 0, 10 } } }, 
    { "DAC_PREAMP_M_LIN", { { DAC_PREAMP_M_LIN, 0, 10 } } }, 
    { "DAC_FC_LIN", { { DAC_FC_LIN, 0, 10 } } }, 
    { "DAC_KRUM_CURR_LIN", { { DAC_KRUM_CURR_LIN, 0, 10 } } }, 
    { "DAC_REF_KRUM_LIN", { { DAC_REF_KRUM_LIN, 0, 10 } } }, 
    { "DAC_COMP_LIN", { { DAC_COMP_LIN, 0, 10 } } }, 
    { "DAC_COMP_TA_LIN", { { DAC_COMP_TA_LIN, 0, 10 } } }, 
    { "DAC_GDAC_L_LIN", { { DAC_GDAC_L_LIN, 0, 10 } } }, 
    { "DAC_GDAC_R_LIN", { { DAC_GDAC_R_LIN, 0, 10 } } }, 
    { "DAC_GDAC_M_LIN", { { DAC_GDAC_M_LIN, 0, 10 } } }, 
    { "DAC_LDAC_LIN", { { DAC_LDAC_LIN, 0, 10 } } }, 
    { "LEACKAGE_FEEDBACK", { { LEACKAGE_FEEDBACK, 0, 2 } } }, 
    { "CFG_VCTRL_LCC", { { LEACKAGE_FEEDBACK, 1, 1 } } }, 
    { "CFG_VCTRL_CF0", { { LEACKAGE_FEEDBACK, 0, 1 } } }, 
    { "VOLTAGE_TRIM", { { VOLTAGE_TRIM, 0, 10 } } }, 
    { "EN_ILIM_VREFA", { { VOLTAGE_TRIM, 9, 1 } } }, 
    { "EN_ILIM_VREFD", { { VOLTAGE_TRIM, 8, 1 } } }, 
    { "TRIM_VREFA", { { VOLTAGE_TRIM, 4, 4 } } }, 
    { "TRIM_VREFD", { { VOLTAGE_TRIM, 0, 4 } } }, 
    { "EnCoreCol_3", { { EnCoreCol_3, 0, 6 } } }, 
    { "EnCoreCol", { { EnCoreCol_0, 0, 16 }, { EnCoreCol_1, 0, 16 }, { EnCoreCol_2, 0, 16 }, { EnCoreCol_3, 0, 6 } } }, 
    { "EnCoreCol_2", { { EnCoreCol_2, 0, 16 } } }, 
    { "EnCoreCol_1", { { EnCoreCol_1, 0, 16 } } }, 
    { "EnCoreCol_0", { { EnCoreCol_0, 0, 16 } } }, 
    { "EnCoreColumnReset_3", { { EnCoreColumnReset_3, 0, 6 } } }, 
    { "EnCoreColumnReset", { { EnCoreColumnReset_0, 0, 16 }, { EnCoreColumnReset_1, 0, 16 }, { EnCoreColumnReset_2, 0, 16 }, { EnCoreColumnReset_3, 0, 6 } } }, 
    { "EnCoreColumnReset_2", { { EnCoreColumnReset_2, 0, 16 } } }, 
    { "EnCoreColumnReset_1", { { EnCoreColumnReset_1, 0, 16 } } }, 
    { "EnCoreColumnReset_0", { { EnCoreColumnReset_0, 0, 16 } } }, 
    { "TriggerConfig", { { TriggerConfig, 0, 10 } } }, 
    { "TwoLevelTrigger", { { TriggerConfig, 9, 1 } } }, 
    { "LatencyConfig", { { TriggerConfig, 0, 9 } } }, 
    { "SelfTriggerConfig_1", { { SelfTriggerConfig_1, 0, 6 } } }, 
    { "SelfTriggerEn", { { SelfTriggerConfig_1, 5, 1 } } }, 
    { "HitOrDigThrEn", { { SelfTriggerConfig_1, 4, 1 } } }, 
    { "HitOrDigThr", { { SelfTriggerConfig_1, 0, 4 } } }, 
    { "SelfTriggerConfig_0", { { SelfTriggerConfig_0, 0, 15 } } }, 
    { "SelfTriggerDelay", { { SelfTriggerConfig_0, 5, 10 } } }, 
    { "SelfTriggerMultiplier", { { SelfTriggerConfig_0, 0, 5 } } }, 
    { "HitOrPatternLUT", { { HitOrPatternLUT, 0, 16 } } }, 
    { "ReadTriggerConfig", { { ReadTriggerConfig, 0, 14 } } }, 
    { "DataReadDelay", { { ReadTriggerConfig, 12, 2 } } }, 
    { "ReadTriggerTimeout", { { ReadTriggerConfig, 0, 12 } } }, 
    { "TruncationTimeoutConf", { { TruncationTimeoutConf, 0, 12 } } }, 
    { "CalibrationConfig", { { CalibrationConfig, 0, 8 } } }, 
    { "DigitalInjectionEnable", { { CalibrationConfig, 7, 1 } } }, 
    { "AnalogInjectionMode", { { CalibrationConfig, 6, 1 } } }, 
    { "CalEdgeFineDelay", { { CalibrationConfig, 0, 6 } } }, 
    { "CLK_DATA_FINE_DELAY", { { CLK_DATA_FINE_DELAY, 0, 12 } } }, 
    { "ClkFineDelay", { { CLK_DATA_FINE_DELAY, 6, 6 } } }, 
    { "DataFineDelay", { { CLK_DATA_FINE_DELAY, 0, 6 } } }, 
    { "VCAL_HIGH", { { VCAL_HIGH, 0, 12 } } }, 
    { "VCAL_MED", { { VCAL_MED, 0, 12 } } }, 
    { "MEAS_CAP", { { MEAS_CAP, 0, 3 } } }, 
    { "EN_INJCAP_PAR_MEAS", { { MEAS_CAP, 2, 1 } } }, 
    { "EN_INJCAP_MEAS", { { MEAS_CAP, 1, 1 } } }, 
    { "SEL_CAL_RANGE", { { MEAS_CAP, 0, 1 } } }, 
    { "CdrConf", { { CdrConf, 0, 4 } } }, 
    { "CdrSelPd", { { CdrConf, 3, 1 } } }, 
    { "CdrSelSerClk", { { CdrConf, 0, 3 } } }, 
    { "ClockEnableConf", { { ClockEnableConf, 0, 12 } } }, 
    { "EnClk40", { { ClockEnableConf, 9, 3 } } }, 
    { "EnClk160", { { ClockEnableConf, 6, 3 } } }, 
    { "EnClkDataMerging", { { ClockEnableConf, 3, 3 } } }, 
    { "EnClkAurora", { { ClockEnableConf, 0, 3 } } }, 
    { "ChSyncConf", { { ChSyncConf, 0, 5 } } }, 
    { "ChSyncThreshold", { { ChSyncConf, 0, 5 } } }, 
    { "GlobalPulseConf", { { GlobalPulseConf, 0, 16 } } }, 
    { "GlobalPulseWidth", { { GlobalPulseWidth, 0, 9 } } }, 
    { "ServiceDataConf", { { ServiceDataConf, 0, 9 } } }, 
    { "EnServiceData", { { ServiceDataConf, 8, 1 } } }, 
    { "ServiceFrameSkip", { { ServiceDataConf, 0, 8 } } }, 
    { "ToTConfig", { { ToTConfig, 0, 13 } } }, 
    { "EnPToTClk640", { { ToTConfig, 12, 1 } } }, 
    { "ToAEnable", { { ToTConfig, 11, 1 } } }, 
    { "ToTDualEdgeCount", { { ToTConfig, 10, 1 } } }, 
    { "ToT6to4Mapping", { { ToTConfig, 9, 1 } } }, 
    { "PToTLatencyAdjust", { { ToTConfig, 0, 9 } } }, 
    { "PrecisionToTEnable_3", { { PrecisionToTEnable_3, 0, 6 } } }, 
    { "PToTEnable", { { PrecisionToTEnable_0, 0, 16 }, { PrecisionToTEnable_1, 0, 16 }, { PrecisionToTEnable_2, 0, 16 }, { PrecisionToTEnable_3, 0, 6 } } }, 
    { "PrecisionToTEnable_2", { { PrecisionToTEnable_2, 0, 16 } } }, 
    { "PrecisionToTEnable_1", { { PrecisionToTEnable_1, 0, 16 } } }, 
    { "PrecisionToTEnable_0", { { PrecisionToTEnable_0, 0, 16 } } }, 
    { "DataMerging", { { DataMerging, 0, 13 } } }, 
    { "DataMergingInputPolarityInvert", { { DataMerging, 9, 4 } } }, 
    { "EnOutputDataChipId", { { DataMerging, 8, 1 } } }, 
    { "EnGatingDataMergeClk1280", { { DataMerging, 7, 1 } } }, 
    { "SelDataMergeClk", { { DataMerging, 6, 1 } } }, 
    { "EnDataMergeLane", { { DataMerging, 2, 4 } } }, 
    { "MergeChBonding", { { DataMerging, 1, 1 } } }, 
    { "DataMergingGpoSel", { { DataMerging, 0, 1 } } }, 
    { "DataMergingMux", { { DataMergingMux, 0, 16 } } }, 
    { "DataMergingInMux_3", { { DataMergingMux, 14, 2 } } }, 
    { "DataMergingInMux_2", { { DataMergingMux, 12, 2 } } }, 
    { "DataMergingInMux_1", { { DataMergingMux, 10, 2 } } }, 
    { "DataMergingInMux_0", { { DataMergingMux, 8, 2 } } }, 
    { "DataMergingOutMux_3", { { DataMergingMux, 6, 2 } } }, 
    { "DataMergingOutMux_2", { { DataMergingMux, 4, 2 } } }, 
    { "DataMergingOutMux_1", { { DataMergingMux, 2, 2 } } }, 
    { "DataMergingOutMux_0", { { DataMergingMux, 0, 2 } } }, 
    { "EnCoreColumnCalibration_3", { { EnCoreColumnCalibration_3, 0, 6 } } }, 
    { "EnCoreColumnCalibration", { { EnCoreColumnCalibration_0, 0, 16 }, { EnCoreColumnCalibration_1, 0, 16 }, { EnCoreColumnCalibration_2, 0, 16 }, { EnCoreColumnCalibration_3, 0, 6 } } }, 
    { "EnCoreColumnCalibration_2", { { EnCoreColumnCalibration_2, 0, 16 } } }, 
    { "EnCoreColumnCalibration_1", { { EnCoreColumnCalibration_1, 0, 16 } } }, 
    { "EnCoreColumnCalibration_0", { { EnCoreColumnCalibration_0, 0, 16 } } }, 
    { "DataConcentratorConf", { { DataConcentratorConf, 0, 12 } } }, 
    { "EnCRC", { { DataConcentratorConf, 11, 1 } } }, 
    { "EnBCId", { { DataConcentratorConf, 10, 1 } } }, 
    { "EnLv1Id", { { DataConcentratorConf, 9, 1 } } }, 
    { "EnEoS", { { DataConcentratorConf, 8, 1 } } }, 
    { "NumOfEventsInStream", { { DataConcentratorConf, 0, 8 } } }, 
    { "CoreColEncoderConf", { { CoreColEncoderConf, 0, 9 } } }, 
    { "BinaryReadOut", { { CoreColEncoderConf, 8, 1 } } }, 
    { "RawData", { { CoreColEncoderConf, 7, 1 } } }, 
    { "MaxHits", { { CoreColEncoderConf, 3, 4 } } }, 
    { "MaxToT", { { CoreColEncoderConf, 0, 3 } } }, 
    { "EnHitsRemoval_3", { { EnHitsRemoval_3, 0, 6 } } }, 
    { "EnHitsRemoval", { { EnHitsRemoval_0, 0, 16 }, { EnHitsRemoval_1, 0, 16 }, { EnHitsRemoval_2, 0, 16 }, { EnHitsRemoval_3, 0, 6 } } }, 
    { "EnHitsRemoval_2", { { EnHitsRemoval_2, 0, 16 } } }, 
    { "EnHitsRemoval_1", { { EnHitsRemoval_1, 0, 16 } } }, 
    { "EnHitsRemoval_0", { { EnHitsRemoval_0, 0, 16 } } }, 
    { "EnIsolatedHitRemoval_3", { { EnIsolatedHitRemoval_3, 0, 6 } } }, 
    { "EnIsolatedHitRemoval", { { EnIsolatedHitRemoval_0, 0, 16 }, { EnIsolatedHitRemoval_1, 0, 16 }, { EnIsolatedHitRemoval_2, 0, 16 }, { EnIsolatedHitRemoval_3, 0, 6 } } }, 
    { "EnIsolatedHitRemoval_2", { { EnIsolatedHitRemoval_2, 0, 16 } } }, 
    { "EnIsolatedHitRemoval_1", { { EnIsolatedHitRemoval_1, 0, 16 } } }, 
    { "EnIsolatedHitRemoval_0", { { EnIsolatedHitRemoval_0, 0, 16 } } }, 
    { "EvenMask", { { EvenMask, 0, 16 } } }, 
    { "OddMask", { { OddMask, 0, 16 } } }, 
    { "EfusesConfig", { { EfusesConfig, 0, 16 } } }, 
    { "EfusesWriteData1", { { EfusesWriteData1, 0, 16 } } }, 
    { "EfusesWriteData", { { EfusesWriteData0, 0, 16 }, { EfusesWriteData1, 0, 16 } } }, 
    { "EfusesWriteData0", { { EfusesWriteData0, 0, 16 } } }, 
    { "AuroraConfig", { { AuroraConfig, 0, 14 } } }, 
    { "SendAltOutput", { { AuroraConfig, 13, 1 } } }, 
    { "EnablePRBS", { { AuroraConfig, 12, 1 } } }, 
    { "ActiveLanes", { { AuroraConfig, 8, 4 } } }, 
    { "CCWait", { { AuroraConfig, 2, 6 } } }, 
    { "CCSend", { { AuroraConfig, 0, 2 } } }, 
    { "AURORA_CB_CONFIG1", { { AURORA_CB_CONFIG1, 0, 8 } } }, 
    { "CBWait", { { AURORA_CB_CONFIG0, 4, 12 }, { AURORA_CB_CONFIG1, 0, 8 } } }, 
    { "AURORA_CB_CONFIG0", { { AURORA_CB_CONFIG0, 0, 16 } } }, 
    { "CBSend", { { AURORA_CB_CONFIG0, 0, 4 } } }, 
    { "AURORA_INIT_WAIT", { { AURORA_INIT_WAIT, 0, 11 } } }, 
    { "AuroraAltOutput_1", { { AuroraAltOutput_1, 0, 4 } } }, 
    { "AuroraAltOutput", { { AuroraAltOutput_0, 0, 16 }, { AuroraAltOutput_1, 0, 4 } } }, 
    { "AuroraAltOutput_0", { { AuroraAltOutput_0, 0, 16 } } }, 
    { "OUTPUT_PAD_CONFIG", { { OUTPUT_PAD_CONFIG, 0, 13 } } }, 
    { "ValReg", { { OUTPUT_PAD_CONFIG, 9, 4 } } }, 
    { "GP_CMOS_EN", { { OUTPUT_PAD_CONFIG, 8, 1 } } }, 
    { "GP_CMOS_DS", { { OUTPUT_PAD_CONFIG, 7, 1 } } }, 
    { "GP_LVDS_EN", { { OUTPUT_PAD_CONFIG, 3, 4 } } }, 
    { "GP_LVDS_BIAS", { { OUTPUT_PAD_CONFIG, 0, 3 } } }, 
    { "GP_CMOS_ROUTE", { { GP_CMOS_ROUTE, 0, 6 } } }, 
    { "GP_LVDS_ROUTE_1", { { GP_LVDS_ROUTE_1, 0, 12 } } }, 
    { "GP_LVDS_PAD3", { { GP_LVDS_ROUTE_1, 6, 6 } } }, 
    { "GP_LVDS_PAD2", { { GP_LVDS_ROUTE_1, 0, 6 } } }, 
    { "GP_LVDS_ROUTE_0", { { GP_LVDS_ROUTE_0, 0, 12 } } }, 
    { "GP_LVDS_PAD1", { { GP_LVDS_ROUTE_0, 6, 6 } } }, 
    { "GP_LVDS_PAD0", { { GP_LVDS_ROUTE_0, 0, 6 } } }, 
    { "DAC_CP_CDR", { { DAC_CP_CDR, 0, 10 } } }, 
    { "DAC_CP_FD_CDR", { { DAC_CP_FD_CDR, 0, 10 } } }, 
    { "DAC_CP_BUFF_CDR", { { DAC_CP_BUFF_CDR, 0, 10 } } }, 
    { "DAC_VCO_CDR", { { DAC_VCO_CDR, 0, 10 } } }, 
    { "DAC_VCOBUFF_CDR", { { DAC_VCOBUFF_CDR, 0, 10 } } }, 
    { "SER_SEL_OUT", { { SER_SEL_OUT, 0, 8 } } }, 
    { "SerSelOut3", { { SER_SEL_OUT, 6, 2 } } }, 
    { "SerSelOut2", { { SER_SEL_OUT, 4, 2 } } }, 
    { "SerSelOut1", { { SER_SEL_OUT, 2, 2 } } }, 
    { "SerSelOut0", { { SER_SEL_OUT, 0, 2 } } }, 
    { "CML_CONFIG", { { CML_CONFIG, 0, 8 } } }, 
    { "SER_INV_TAP", { { CML_CONFIG, 6, 2 } } }, 
    { "SER_EN_TAP", { { CML_CONFIG, 4, 2 } } }, 
    { "SER_EN_LANE", { { CML_CONFIG, 0, 4 } } }, 
    { "DAC_CML_BIAS_2", { { DAC_CML_BIAS_2, 0, 10 } } }, 
    { "DAC_CML_BIAS_1", { { DAC_CML_BIAS_1, 0, 10 } } }, 
    { "DAC_CML_BIAS_0", { { DAC_CML_BIAS_0, 0, 10 } } }, 
    { "MonitorConfig", { { MonitorConfig, 0, 13 } } }, 
    { "MonitorEnable", { { MonitorConfig, 12, 1 } } }, 
    { "IMonitor", { { MonitorConfig, 6, 6 } } }, 
    { "VMonitor", { { MonitorConfig, 0, 6 } } }, 
    { "ErrWngMask", { { ErrWngMask, 0, 8 } } }, 
    { "MON_SENS_SLDO", { { MON_SENS_SLDO, 0, 12 } } }, 
    { "MON_SENS_SLDOD_EN", { { MON_SENS_SLDO, 11, 1 } } }, 
    { "MON_SENS_SLDOD_DEM", { { MON_SENS_SLDO, 7, 4 } } }, 
    { "MON_SENS_SLDOD_SELBIAS", { { MON_SENS_SLDO, 6, 1 } } }, 
    { "MON_SENS_SLDOA_EN", { { MON_SENS_SLDO, 5, 1 } } }, 
    { "MON_SENS_SLDOA_DEM", { { MON_SENS_SLDO, 1, 4 } } }, 
    { "MON_SENS_SLDOA_SELBIAS", { { MON_SENS_SLDO, 0, 1 } } }, 
    { "MON_SENS_ACB", { { MON_SENS_ACB, 0, 6 } } }, 
    { "MON_SENS_ACB_EN", { { MON_SENS_ACB, 5, 1 } } }, 
    { "MON_SENS_ACB_DEM", { { MON_SENS_ACB, 1, 4 } } }, 
    { "MON_SENS_ACB_SELBIAS", { { MON_SENS_ACB, 0, 1 } } }, 
    { "MON_ADC", { { MON_ADC, 0, 9 } } }, 
    { "Vref_Rsens_Top", { { MON_ADC, 8, 1 } } }, 
    { "Vref_Rsens_Bot", { { MON_ADC, 7, 1 } } }, 
    { "Vref_in", { { MON_ADC, 6, 1 } } }, 
    { "MON_ADC_TRIM", { { MON_ADC, 0, 6 } } }, 
    { "DAC_NTC", { { DAC_NTC, 0, 10 } } }, 
    { "HITOR_MASK_3", { { HITOR_MASK_3, 0, 6 } } }, 
    { "HitOr_Mask", { { HITOR_MASK_0, 0, 16 }, { HITOR_MASK_1, 0, 16 }, { HITOR_MASK_2, 0, 16 }, { HITOR_MASK_3, 0, 6 } } }, 
    { "HITOR_MASK_2", { { HITOR_MASK_2, 0, 16 } } }, 
    { "HITOR_MASK_1", { { HITOR_MASK_1, 0, 16 } } }, 
    { "HITOR_MASK_0", { { HITOR_MASK_0, 0, 16 } } }, 
    { "AutoRead0", { { AutoRead0, 0, 9 } } }, 
    { "AutoRead1", { { AutoRead1, 0, 9 } } }, 
    { "AutoRead2", { { AutoRead2, 0, 9 } } }, 
    { "AutoRead3", { { AutoRead3, 0, 9 } } }, 
    { "AutoRead4", { { AutoRead4, 0, 9 } } }, 
    { "AutoRead5", { { AutoRead5, 0, 9 } } }, 
    { "AutoRead6", { { AutoRead6, 0, 9 } } }, 
    { "AutoRead7", { { AutoRead7, 0, 9 } } }, 
    { "RingOscConfig", { { RingOscConfig, 0, 15 } } }, 
    { "RingOscBClear", { { RingOscConfig, 14, 1 } } }, 
    { "RingOscBEnBL", { { RingOscConfig, 13, 1 } } }, 
    { "RingOscBEnBR", { { RingOscConfig, 12, 1 } } }, 
    { "RingOscBEnCAPA", { { RingOscConfig, 11, 1 } } }, 
    { "RingOscBEnFF", { { RingOscConfig, 10, 1 } } }, 
    { "RingOscBEnLVT", { { RingOscConfig, 9, 1 } } }, 
    { "RingOscAClear", { { RingOscConfig, 8, 1 } } }, 
    { "RingOscAEnable", { { RingOscConfig, 0, 8 } } }, 
    { "RingOscRoute", { { RingOscRoute, 0, 9 } } }, 
    { "RingOscARoute", { { RingOscRoute, 6, 3 } } }, 
    { "RingOscBRoute", { { RingOscRoute, 0, 6 } } }, 
    { "RING_OSC_A_OUT", { { RING_OSC_A_OUT, 0, 16 } } }, 
    { "RING_OSC_B_OUT", { { RING_OSC_B_OUT, 0, 16 } } }, 
    { "BCIDCnt", { { BCIDCnt, 0, 16 } } }, 
    { "TrigCnt", { { TrigCnt, 0, 16 } } }, 
    { "ReadTrigCnt", { { ReadTrigCnt, 0, 16 } } }, 
    { "LockLossCnt", { { LockLossCnt, 0, 16 } } }, 
    { "BitFlipWngCnt", { { BitFlipWngCnt, 0, 16 } } }, 
    { "BitFlipErrCnt", { { BitFlipErrCnt, 0, 16 } } }, 
    { "CmdErrCnt", { { CmdErrCnt, 0, 16 } } }, 
    { "RdWrFifoErrorCount", { { RdWrFifoErrorCount, 0, 16 } } }, 
    { "AI_REGION_ROW", { { AI_REGION_ROW, 0, 9 } } }, 
    { "HitOr_3_Cnt", { { HitOr_3_Cnt, 0, 16 } } }, 
    { "HitOr_2_Cnt", { { HitOr_2_Cnt, 0, 16 } } }, 
    { "HitOr_1_Cnt", { { HitOr_1_Cnt, 0, 16 } } }, 
    { "HitOr_0_Cnt", { { HitOr_0_Cnt, 0, 16 } } }, 
    { "PixelSEUCnt", { { PixelSEUCnt, 0, 16 } } }, 
    { "GlobalConfigSEUCnt", { { GlobalConfigSEUCnt, 0, 16 } } }, 
    { "SkippedTriggerCnt", { { SkippedTriggerCnt, 0, 16 } } }, 
    { "EfusesReadData1", { { EfusesReadData1, 0, 16 } } }, 
    { "EfusesReadData0", { { EfusesReadData0, 0, 16 } } }, 
    { "MonitoringDataADC", { { MonitoringDataADC, 0, 12 } } }, 
    { "SEU00", { { SEU00, 0, 16 } } }, 
    { "SEU01", { { SEU01, 0, 16 } } }, 
    { "SEU02", { { SEU02, 0, 16 } } }, 
    { "SEU03", { { SEU03, 0, 16 } } }, 
    { "SEU04", { { SEU04, 0, 16 } } }, 
    { "SEU05", { { SEU05, 0, 16 } } }, 
    { "SEU06", { { SEU06, 0, 16 } } }, 
    { "SEU07", { { SEU07, 0, 16 } } }, 
    { "SEU08", { { SEU08, 0, 16 } } }, 
    { "SEU_nodel_00", { { SEU_nodel_00, 0, 16 } } }, 
    { "SEU_nodel_01", { { SEU_nodel_01, 0, 16 } } }, 
    { "SEU_nodel_02", { { SEU_nodel_02, 0, 16 } } }, 
    { "SEU_nodel_03", { { SEU_nodel_03, 0, 16 } } }, 
    { "SEU_nodel_04", { { SEU_nodel_04, 0, 16 } } }, 
    { "SEU_nodel_05", { { SEU_nodel_05, 0, 16 } } }, 
    { "SEU_nodel_06", { { SEU_nodel_06, 0, 16 } } }, 
    { "SEU_nodel_07", { { SEU_nodel_07, 0, 16 } } }, 
    { "SEU_nodel_08", { { SEU_nodel_08, 0, 16 } } }, 
    { "SEU_nodel_09", { { SEU_nodel_09, 0, 16 } } }, 
    { "SEU_nodel_10", { { SEU_nodel_10, 0, 16 } } }, 
    { "SEU_nodel_11", { { SEU_nodel_11, 0, 16 } } }, 
    { "SEU_nodel_12", { { SEU_nodel_12, 0, 16 } } }, 
    { "SEU_nodel_13", { { SEU_nodel_13, 0, 16 } } }, 
    { "SEU_nodel_14", { { SEU_nodel_14, 0, 16 } } }, 
    { "SEU_nodel_15", { { SEU_nodel_15, 0, 16 } } }, 
    { "SEU_nodel_16", { { SEU_nodel_16, 0, 16 } } }, 
    { "SEU_nodel_17", { { SEU_nodel_17, 0, 16 } } }, 
    { "SEU_nodel_18", { { SEU_nodel_18, 0, 16 } } }, 
    { "SEU_nodel_19", { { SEU_nodel_19, 0, 16 } } }, 
    { "SEU_nodel_20", { { SEU_nodel_20, 0, 16 } } }, 
    { "SEU_nodel_21", { { SEU_nodel_21, 0, 16 } } }, 
    { "SEU_nodel_22", { { SEU_nodel_22, 0, 16 } } }, 
    { "SEU_nodel_23", { { SEU_nodel_23, 0, 16 } } }, 
    { "SEU_nodel_24", { { SEU_nodel_24, 0, 16 } } }, 
    { "SEU_nodel_25", { { SEU_nodel_25, 0, 16 } } }, 
    { "SEU_nodel_26", { { SEU_nodel_26, 0, 16 } } }, 
    { "SEU_nodel_27", { { SEU_nodel_27, 0, 16 } } }, 
    { "SEU_nodel_28", { { SEU_nodel_28, 0, 16 } } }, 
    { "SEU_nodel_29", { { SEU_nodel_29, 0, 16 } } }, 
    { "SEU_nodel_30", { { SEU_nodel_30, 0, 16 } } }, 
    { "SEU_nodel_31", { { SEU_nodel_31, 0, 16 } } }, 
    { "SEU00_notmr", { { SEU00_notmr, 0, 16 } } }, 
    { "SEU01_notmr", { { SEU01_notmr, 0, 16 } } }, 
    { "SEU02_notmr", { { SEU02_notmr, 0, 16 } } }, 
    { "SEU03_notmr", { { SEU03_notmr, 0, 16 } } }, 
    { "SEU04_notmr", { { SEU04_notmr, 0, 16 } } }, 
    { "SEU05_notmr", { { SEU05_notmr, 0, 16 } } }, 
    { "SEU06_notmr", { { SEU06_notmr, 0, 16 } } }, 
    { "SEU07_notmr", { { SEU07_notmr, 0, 16 } } }, 
    { "SEU08_notmr", { { SEU08_notmr, 0, 16 } } }, 
    { "SEU09_notmr", { { SEU09_notmr, 0, 16 } } }, 
    { "SEU10_notmr", { { SEU10_notmr, 0, 16 } } }, 
    { "SEU11_notmr", { { SEU11_notmr, 0, 16 } } }, 
    { "SEU12_notmr", { { SEU12_notmr, 0, 16 } } }, 
    { "SEU13_notmr", { { SEU13_notmr, 0, 16 } } }, 
    { "SEU14_notmr", { { SEU14_notmr, 0, 16 } } }, 
    { "SEU15_notmr", { { SEU15_notmr, 0, 16 } } }, 
    { "SEU16_notmr", { { SEU16_notmr, 0, 16 } } }, 
    { "SEU17_notmr", { { SEU17_notmr, 0, 16 } } }, 
    { "SEU18_notmr", { { SEU18_notmr, 0, 16 } } }, 
    { "SEU19_notmr", { { SEU19_notmr, 0, 16 } } }, 
    { "SEU20_notmr", { { SEU20_notmr, 0, 16 } } }, 
    { "SEU21_notmr", { { SEU21_notmr, 0, 16 } } }, 
    { "SEU22_notmr", { { SEU22_notmr, 0, 16 } } }, 
    { "SEU23_notmr", { { SEU23_notmr, 0, 16 } } }, 
    { "SEU24_notmr", { { SEU24_notmr, 0, 16 } } }, 
    { "SEU25_notmr", { { SEU25_notmr, 0, 16 } } }, 
    { "SEU26_notmr", { { SEU26_notmr, 0, 16 } } }, 
    { "SEU27_notmr", { { SEU27_notmr, 0, 16 } } }, 
    { "SEU28_notmr", { { SEU28_notmr, 0, 16 } } }, 
    { "SEU29_notmr", { { SEU29_notmr, 0, 16 } } }, 
    { "SEU30_notmr", { { SEU30_notmr, 0, 16 } } }, 
    { "SEU31_notmr", { { SEU31_notmr, 0, 16 } } }, 
    { "SEU32_notmr", { { SEU32_notmr, 0, 16 } } }, 
    { "SEU33_notmr", { { SEU33_notmr, 0, 16 } } }, 
    { "SEU34_notmr", { { SEU34_notmr, 0, 16 } } }, 
    { "SEU35_notmr", { { SEU35_notmr, 0, 16 } } }, 
    { "SEU36_notmr", { { SEU36_notmr, 0, 16 } } }, 
    { "SEU37_notmr", { { SEU37_notmr, 0, 16 } } }, 
    { "SEU38_notmr", { { SEU38_notmr, 0, 16 } } }, 
    { "SEU39_notmr", { { SEU39_notmr, 0, 16 } } }, 
    { "SEU40_notmr", { { SEU40_notmr, 0, 16 } } }, 
    { "SEU41_notmr", { { SEU41_notmr, 0, 16 } } }, 
    { "SEU42_notmr", { { SEU42_notmr, 0, 16 } } }, 
    { "SEU43_notmr", { { SEU43_notmr, 0, 16 } } }, 
    { "SEU44_notmr", { { SEU44_notmr, 0, 16 } } }, 
    { "SEU45_notmr", { { SEU45_notmr, 0, 16 } } }, 
    { "SEU46_notmr", { { SEU46_notmr, 0, 16 } } }, 
    { "SEU47_notmr", { { SEU47_notmr, 0, 16 } } }, 
    { "SEU48_notmr", { { SEU48_notmr, 0, 16 } } }, 
    { "SEU49_notmr", { { SEU49_notmr, 0, 16 } } }, 
    { "SEU50_notmr", { { SEU50_notmr, 0, 16 } } }, 
    { "SEU51_notmr", { { SEU51_notmr, 0, 16 } } }, 
    { "SEU52_notmr", { { SEU52_notmr, 0, 16 } } }, 
    { "SEU53_notmr", { { SEU53_notmr, 0, 16 } } }, 
    { "SEU54_notmr", { { SEU54_notmr, 0, 16 } } }, 
    { "SEU55_notmr", { { SEU55_notmr, 0, 16 } } }, 
    { "SEU56_notmr", { { SEU56_notmr, 0, 16 } } }, 
    { "SEU57_notmr", { { SEU57_notmr, 0, 16 } } }, 
    { "SEU58_notmr", { { SEU58_notmr, 0, 16 } } }, 
    { "SEU59_notmr", { { SEU59_notmr, 0, 16 } } }, 
    { "SEU60_notmr", { { SEU60_notmr, 0, 16 } } }, 
    { "SEU61_notmr", { { SEU61_notmr, 0, 16 } } }, 
    { "SEU62_notmr", { { SEU62_notmr, 0, 16 } } }, 
    { "SEU63_notmr", { { SEU63_notmr, 0, 16 } } }
};

}

}