[RegReader]
type = "RD53BRegReader"
args = {}

[RegTest]
type = "RD53BRegTest"
args = { testRegs = true, testPixels = true, ServiceFrameSkip = 50 }

[DigitalScan]
type = "RD53BInjectionTool"

[DigitalScan.args]
injectionType = "Digital"
nInjections = 10
triggerDuration = 4
triggerLatency = 134
offset = [0, 0]
size = [0, 0]
maskGen = [
    { dim = 0, size = 0, parallel = false, shift = [8, 1] },
    { dim = 1, size = 0, parallel = true, shift = [] },
    { dim = 0, size = 21, parallel = true, shift = [] }
]
showPlots = true

[AnalogScan]
type = "RD53BInjectionTool"

[AnalogScan.args]
injectionType = "Analog"
nInjections = 50
triggerDuration = 2
triggerLatency = 134
injectionPeriod = 800
offset = [0, 0]
size = [0, 0]
maskGen = [
    { dim = 0, size = 0, parallel = false, shift = [8, 1] },
    { dim = 1, size = 0, parallel = true, shift = [] },
    { dim = 0, size = 21, parallel = true, shift = [] }
]
showPlots = true

[ThresholdScanInjection]
type = "RD53BInjectionTool"

[ThresholdScanInjection.args]
injectionType = "Analog"
nInjections = 100
triggerDuration = 2
triggerLatency = 134
injectionPeriod = 1000
offset = [0, 0]
size = [0, 0]
maskGen = [
    { dim = 0, size = 0, parallel = false, shift = [8, 1] },
    { dim = 1, size = 0, parallel = true, shift = [] },
    { dim = 0, size = 21, parallel = true, shift = [] }
]

[ThresholdScan]
type = "RD53BThresholdScan"
args = { injectionTool = "ThresholdScanInjection", vcalMed = 300, vcalHighRange = [600, 2100], vcalHighStep = 50 }

[ThresholdEqualization]
type = "RD53BThresholdEqualization"

[ThresholdEqualization.args]
thresholdScan = "ThresholdScan"
injectionTool = "ThresholdScanInjection"
targetThreshold = 0 # The Delta VCAL value to tune the threshold at. If it's 0 a threshold scan will be performed and the mean trheshold will be used.

[RingOsc]
type = "RD53RingOscillator"
args = {}

[ShortRingOsc]
type = "RD53ShortRingOscillator"
args = {}

[MuxScan]
type = "RD53MuxScan"
args = {}

[IVScan]
type = "RD53IVScan"
args = { configFile = "/home/cms/works/power_supply/config/iv_it_croc_sldo.xml", type = "steps", powerSupplyName = "TTi_MX", multimeterName = "KeithleyMultimeter", powerSupplyVoltageProtection = 3.0, scanPointCurrentRange = [0.5, 2.0], scanPointCurrentStep = 0.1}

[ADCScan]
type = "RD53ADCScan"
args = {}

[DACScan]
type = "RD53DACScan"
args = {}

[TempSensor]
type = "RD53TempSensor"
args = {}

[ShortTempSensor]
type = "RD53ShortTempSensor"
args = {}

[VrefTrimming]
type = "RD53VrefTrimming"
args = {}

