[Pixels]
tdac = "tdac.csv"

# Select core column ranges to be disabled (all core columns are enabled by default).
# eg.: [[0, 16], [32, 64]]
[CoreColumns]
disable = [] 
disableInjections = []

# Set chip registers.
[Registers]
