[RegReader]
type = "RD53BRegReader"
args = {}

[DigitalScan]
type = "RD53BInjectionTool"

[DigitalScan.args]
injectionType = "Digital"
nInjections = 10
triggerDuration = 4
triggerLatency = 134
offset = [0, 0]
size = [0, 0]
maskGen = [
    { dim = 0, size = 0, parallel = false, shift = [8, 1] },
    { dim = 1, size = 0, parallel = true, shift = [] },
    { dim = 0, size = 21, parallel = true, shift = [] }
]

[AnalogScan]
type = "RD53BInjectionTool"

[AnalogScan.args]
injectionType = "Analog"
nInjections = 50
triggerDuration = 2
triggerLatency = 134
injectionPeriod = 800
offset = [0, 0]
size = [0, 0]
maskGen = [
    { dim = 0, size = 0, parallel = false, shift = [8, 1] },
    { dim = 1, size = 0, parallel = true, shift = [] },
    { dim = 0, size = 21, parallel = true, shift = [] }
]

[ThresholdScanInjection]
type = "RD53BInjectionTool"

[ThresholdScanInjection.args]
injectionType = "Analog"
nInjections = 100
triggerDuration = 2
triggerLatency = 134
injectionPeriod = 1000
offset = [0, 0]
size = [0, 0]
maskGen = [
    { dim = 0, size = 0, parallel = false, shift = [8, 1] },
    { dim = 1, size = 0, parallel = true, shift = [] },
    { dim = 0, size = 21, parallel = true, shift = [] }
]

[ThresholdScan]
type = "RD53BThresholdScan"
args = { injectionTool = "ThresholdScanInjection", vcalMed = 300, vcalHighRange = [600, 2100], vcalHighStep = 50 }

[RingOsc]
type = "RD53BRingOscillator"
args = {}