[RegReader]
type = "RD53BRegReader"
args = {}

[DigitalScan]
type = "RD53BInjectionTool"
args = { injectionType = "Digital", nInjections = 10, triggerDuration = 2, triggerLatency = 134, hitsPerCol = 21, offset = [0, 0], size = [0, 0] }

[AnalogScan]
type = "RD53BInjectionTool"
args = { injectionType = "Analog", nInjections = 10, triggerDuration = 2, triggerLatency = 134, hitsPerCol = 8, offset = [0, 0], size = [0, 0], injectionPeriod = 200 }


[ThresholdScanInjection]
type = "RD53BInjectionTool"
args = { injectionType = "Analog", nInjections = 100, triggerDuration = 2, triggerLatency = 134, hitsPerCol = 21 }

[ThresholdScan]
type = "RD53BThresholdScan"
args = { injectionTool = "ThresholdScanInjection", vcalMed = 300, vcalHighRange = [600, 2100], vcalHighStep = 50 }

[RingOsc]
type = "RD53RingOscillator"
args = {}

[ShortRingOsc]
type = "RD53ShortRingOscillator"
args = {}

[MuxScan]
type = "RD53MuxScan"
args = {}

[ADCScan]
type = "RD53ADCScan"
args = {}

[DACScan]
type = "RD53DACScan"
args = {}

[TempSens]
type = "RD53TempSens"
args = {}


